//PROGRAM_START
#include "lib.h"//[[0]]
//[[1]]
int main(int argc, char* argv[]) {//[[2]]
  char buffer[20];//[[3]]
  int matrix[25][25];//[[4]]
  //[[5]]
  for (int i = 0; i < 25; i++) {//[[6]]
    for (int j = 0; j < 25; j++) {//[[7]]
      matrix[i][j] = 1;//[[8]]
    }//[[9]]
  }//[[10]]
//[[11]]
  unsigned int sum = 0;//[[12]]
  for (int i = 0; i < 25; i++) {//[[13]]
    for (int j = 0; j < 25; j++) {//[[14]]
      sum += matrix[i][j];//[[15]]
    }//[[16]]
  }//[[17]]
//[[18]]
  uns_to_str(buffer, sum);//[[19]]
  print_string(buffer);//[[20]]
  print_string("\n");//[[21]]
  return 0;//[[22]]
}//[[23]]
//[[24]]
//PROGRAM_END